# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/diffusion',
                'doc_host': 'https://g-wiedemair.github.io',
                'git_url': 'https://github.com/g-wiedemair/diffusion',
                'lib_path': 'diffusion'},
  'syms': {'diffusion.core': {'diffusion.core.foo': ('core.html#foo', 'diffusion/core.py')}}}
