# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['inplace']

# %% ../nbs/00_core.ipynb 3
def inplace(f):
    def _f(b):
        f(b)
        return b
    return _f
