# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['def_device', 'inplace', 'to_device']

# %% ../nbs/00_core.ipynb 2
import torch

# %% ../nbs/00_core.ipynb 3
def inplace(f):
    def _f(b):
        f(b)
        return b
    return _f

# %% ../nbs/00_core.ipynb 4
from typing import Mapping

def_device = 'mps' if torch.backends.mps.is_available() else 'cuda' if torch.cuda.is_available() else 'cpu'

def to_device(x, device=def_device):
    if isinstance(x, torch.Tensor): return x.to(device)
    if isinstance(x, Mapping): return {k:v.to(device) for k,v in x.items()}
    return type(x)(to_device(o, device) for o in x)

