# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/205_learner.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/205_learner.ipynb 1
import fastcore.all as fc 
from .core import to_device
import torch
from torch import optim,nn
import matplotlib as mpl

