# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/205_learner.ipynb.

# %% auto 0
__all__ = ['CancelFitException', 'CancelBatchException', 'CancelEpochException', 'Callback', 'run_cbs', 'SingleBatchCB']

# %% ../nbs/205_learner.ipynb 1
import fastcore.all as fc 
from .core import to_device, def_device
import torch
from torch import optim,nn,tensor
import torch.nn.functional as F
import matplotlib as mpl


# %% ../nbs/205_learner.ipynb 13
class CancelFitException(Exception): pass
class CancelBatchException(Exception): pass
class CancelEpochException(Exception): pass

# %% ../nbs/205_learner.ipynb 14
class Callback(): order = 0

# %% ../nbs/205_learner.ipynb 15
from operator import attrgetter

def run_cbs(cbs, method_nm, learn=None):
    for cb in sorted(cbs, key=attrgetter('order')):
        method = getattr(cb, method_nm, None)
        if method is not None: method(learn)

# %% ../nbs/205_learner.ipynb 21
class SingleBatchCB(Callback):
    order = 1
    def after_batch(self, learn): raise CancelFitException()
